apiVersion: v1
kind: Service
metadata:
  name: github-nginx-cache-loadbalancer
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: github-nginx-cache
  type: LoadBalancer
