pool:
  vmImage: "Ubuntu 16.04"

trigger:
  - master

steps:
  - task: Docker@2
    displayName: Build docker container
    inputs:
      command: build
      arguments: -t testbuild

  - task: Docker@2
    displayName: Run docker container
    inputs:
      command: run
      arguments: -p 8000:80 -d testbuild

  - script: sudo apt install libcurl4-openssl-dev libssl-dev
    displayName: "Install build dependencies"
    workingDirectory: ./test

  - script: npm -s ci
    displayName: "Install dependencies"
    workingDirectory: ./test

  - script: npm run -s test
    displayName: "Run tests"
    workingDirectory: ./test
