pool:
  vmImage: "Ubuntu 20.04"

trigger:
  - main

steps:
  - task: Docker@2
    displayName: Build docker container
    inputs:
      command: build
      arguments: -t testbuild

  - task: Docker@2
    displayName: Run docker container
    inputs:
      command: run
      arguments: -p 8000:80 -d testbuild

  - script: npm ci
    displayName: "Install dependencies"
    workingDirectory: ./test

  - script: npm run test
    displayName: "Run tests"
    workingDirectory: ./test
